### ISSUE TITLE
Add support to query all and range of values from LocalStateStore

### ISSUE THREAD

**Issue by jeqo** [lightbend/kafka-streams-query#7]
Expand LocalStateStoreQuery to support all KafkaStreams `store` methods:
* `all: KeyValueIterator[K, V]`
* `range(from: K, to: K): KeyValueIterator[K, V]`
* `approximateNumEntries: Long`

Or just exposing `KeyValueStore` could be enough.

**Comment by debasishg** [comment]
We have plans of supporting this.

**Comment by debasishg** [comment]
I was giving some thought to publishing the APIs `all` and `range`. 

The core APIs in Kafka Streams return `KeyValueIterator`. Bt what should be the return type in a distributed setting ? It can be `List[KeyValueIterator]` because realizing all the collections and returning `List[V]` doesn't make sense in a really big data scenario. But then what does it mean by returning a bunch of iterators from an http endpoint ?

**Comment by jeqo** [comment]
I'd say that a `List[(K,V)]` is enough. 
I understand the risk of parsing the iterator into a list and returning it back to the client a potentially big  when you have a huge table, but it will be developer responsibility to filter the table accordingly, IMHO.

**Comment by debasishg** [comment]
ok .. `all` possibly makes sense this way. We can iterate over all hosts which has this store name and collect the key/value pairs. But I don't think `range` makes any sense in the distributed setting. The `fromKey` and `toKey` may be from different hosts and the API will fail .. Possibly the API makes sense only when *both the keys* are on the same host. Or else fail the API ..

**Comment by jeqo** [comment]
I don't see much difference between how `all` and `range` will get implemented: both will go to all instances to get and join values, if host does not find values locally, it will return an empty list. Let me know if I'm missing something.

BTW: I'm primarily interested in using `LocalStateStoreQuery` directly.

**Comment by debasishg** [comment]
`all` is straightforward. But when u specify `range` there looks like an upper and lower bound in the keyset to be fetched. This makes perfect sense when we are talking about one store in one node. But how does it work when we have `fromKey` in one host `h1` and `toKey` in another host `h2`. The APIs that Kafka Streams give on `ReadOnlyKeyValueStore` is only for a *local* store. Hence what I am thinking is that `range` should work only if both the key bounds are on the same host.

**Comment by jeqo** [comment]
> But how does it work when we have fromKey in one host h1 and toKey in another host h2. 

If you send `range(from, to)` to `h1` and `h2`, I'd expect that if I join those I would get the complete range. I'd like to check first locally, though. 

Also, what would happened if a client is using `GlobalKTable`? Maybe we can add fetch APIs for only local store?

`fetchFromLocal(...)`, `fetchAllFromLocal(...)`, `fetchRangeFromLocal(...)`

**Comment by debasishg** [comment]
> If you send `range(from, to)` to `h1` and `h2`, I'd expect that if I join those I would get the complete range. I'd like to check first locally, though.

if I send `range(from, to)` to `h1`, the `ReadOnlyKeyValueStore` being local, will not be able to serve the query since `to` is NOT in `h1`. Possibly I am missing what u mean by **join** here ..

**Comment by jeqo** [comment]
From your PR I consider this as joining results: 
`case hosts => Future.traverse(hosts)(fetchKVs).map(_.flatten)`
make sense? 

From `range` API in `ReadOnlyKeyValueStore` it does not specify that `to` must be present to return a result, but as I said, I'd like to test this local first. 

In any case, we can add `range` at the `LocalStateStoreQuery` level and keep all at the HTTP level right? 

WDYT about `...FromLocal` APIs?

**Comment by debasishg** [comment]
So, what u r saying is ..

`all` : traverse through all hosts
`range` : traverse through the host pair for (`fromKey` and `toKey`) - is this the correct desired semantics ?

> In any case, we can add range at the LocalStateStoreQuery level and keep all at the HTTP level right?

It's added in the changes that I am making .. https://github.com/lightbend/kafka-streams-query/blob/more-kv-query/lib/src/main/scala/com/lightbend/kafka/scala/iq/services/LocalStateStoreQuery.scala#L69

> WDYT about `...FromLocal` APIs?

Effectively the APIs in `LocalStateStoreQuery` are local APIs - right ? You mean propagating them up to http level through fetch APIs ? I think it can be done ..

**Comment by jeqo** [comment]
> range : traverse through the host pair for (fromKey and toKey) - is this the correct desired semantics ?

Yes. traversing through the hosts will return the expected result.

> It's added in the changes that I am making .. https://github.com/lightbend/kafka-streams-query/blob/more-kv-query/lib/src/main/scala/com/lightbend/kafka/scala/iq/services/LocalStateStoreQuery.scala#L69

:+1: 

> Effectively the APIs in LocalStateStoreQuery are local APIs - right ? You mean propagating them up to http level through fetch APIs ? I think it can be done ..

Yes. What I was more concerned about where cases when you use KGlobalTable, and values from all partitions are in every node (https://cwiki.apache.org/confluence/display/KAFKA/KIP-99%3A+Add+Global+Tables+to+Kafka+Streams). If `metadataService#streamsMetadtaForStore` returns all instance with a store that contains a Global Table you could end up with a list of repeated values. (I think this could be discussed in a different issue)

**Comment by debasishg** [comment]
> Yes. traversing through the hosts will return the expected result.
I am still not sure how this will give the correct result. There's some byte ordering based on which the range between `fromKey` and `toKey` will be computed. If we were on a single application there will be (say) `n` entries in the range. How can we ensure that in the distributed model we will have the same entries for the range ? If we pick all entries from host where `fromKey` is present, we will get entries which would not be there in the single instance case ..

I have posted a question on kafka users mailing list ..

**Comment by debasishg** [comment]
We now have a version of `fetchRange` that should work .. https://github.com/lightbend/kafka-streams-query/blob/more-kv-query/lib/src/main/scala/com/lightbend/kafka/scala/iq/http/KeyValueFetcher.scala#L91

**Comment by jeqo** [comment]
LGTM thanks!!
